### ISSUE TITLE
How to write the jdbc:virtuoso connection string for Openlink Virtuoso community server?

### ISSUE THREAD

**Issue by fishfree** [danielhmills/virtuoso-to-neo4j-handler#2]
![image](https://github.com/user-attachments/assets/0cbef01d-ef30-4a05-9bb3-051ca7ced368)
My HTTP SPARQL endpoint is `http://localhost:8890/sparql` with no user or password.

**Comment by danielhmills** [comment]
The Virtuoso JDBC driver uses the SQL Listening Port Value (Default Value = *1111*).

If this value hasn't been changed, Replacing `localhost:8890`, with `localhost:1111` in your JDBC connection URL should resolve this error.

If the SQL Listening Port value was manually changed, the value can be found by looking at the `ServerPort` value in the `[Parameters]` section of the **virtuoso.ini** file in your Virtuoso installation's *database* directory.

**Comment by danielhmills** [comment]
Hi @fishfree,

The basic JDBC URL for Virtuoso uses the following pattern:

`jdbc:virtuoso://<Hostname>:<Port#>//UID=<user name>/PWD=<password>/`

**1111** is the default port number for the SQL Listening port used with the JDBC driver. 

If you haven't changed the port number, you can also use:

`jdbc:virtuoso//localhost//UID=<user name>/PWD=<password>`

This will also use the default SQL listener port number (1111).

<img width="1502" alt="Screenshot 2024-08-28 at 3 34 55 PM" src="https://github.com/user-attachments/assets/3c380051-c97f-49f9-bf9b-f42dcda98958">

SPARQL query functionality is invoked by adding `SPARQL` to the beginning of your query (This is already included in line 4 of the image you sent).

Additional Info:
* [Virtuoso Driver For JDBC URL Format](https://docs.openlinksw.com/virtuoso/jdbcurl4mat/)
* [SPARQL-within-SQL Functionality](https://medium.com/virtuoso-blog/spasql-about-8486deecba66)

I have also updated the readme to include the JDBC URL format.

**Comment by fishfree** [comment]
@danielhmills Thank you for your tip! I found I forgot to map the 1111 port on my Virtuoso container.
